baseURL: "https://unb-mds.github.io/Projeto-B.I.I.A/"
languageCode: "pt-br"
title: "MDS - Documentação"

# Configurações básicas
disableKinds: ["taxonomy", "term"]
enableRobotsTXT: true

# Menus (URLs hardcoded no template)
# menu:
#   main:
#     - identifier: "home"
#       name: "Home"
#       url: "https://ananunesv.github.io/teste/"
#       weight: 1
#     - identifier: "sprint"
#       name: "Sprints"
#       url: "https://ananunesv.github.io/teste/sprint/"
#       weight: 2
#     - identifier: "arquitetura"
#       name: "Arquitetura"
#       url: "https://ananunesv.github.io/teste/arquitetura/"
#       weight: 3
